apiVersion: v1
kind: Service
metadata:
  name: task-mongo-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: task-mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-mongo
  template:
    metadata:
      labels:
        app: task-mongo
    spec:
      containers:
        - name: task-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: task-mongo-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: task-mongo-storage
          persistentVolumeClaim:
            claimName: task-mongo-pvc